language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database localhost;create database kanban_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
