language: ruby
rvm:
  - 2.3.1
  - 2.4.0-preview1
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database kanban_test;' -U postgres
  - psql -c 'create database localhost;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
