version: '2'
services:
  db:
    image: "postgres:9.5"
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker-volumes/kanban/db/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
  web:
    build: .
    command: /kanban/bin/start
    volumes:
      - .:/kanban
      - ~/.docker-volumes/kanban/web/bundle:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "db"
