db:
  image: "postgres:9.4.0"
  volumes:
    - ~/.docker-volumes/kanban/db/:/var/lib/postgresql/data/
  environment:
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: "postgres"
  ports:
    - "5432:5432"
  expose:
    - "5432"
