# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 922bf635ef1c6a314ac37c75d0a750f386f9fa05a3aa19a686d5a1254b27bf08be6aa2e8950bbeff038515b46ac77601a6f920f06a3598accba986976696d43b

test:
  secret_key_base: 52b32c93fcda3613cf6df4b92ef820deea83cf914e7d7dd93bf4ae643c94f69d129a64bd7c6d823002e21fcaecb3eb83d20f135fb8282fb1f7d3454603a7ff9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
